caltech256_classnames = ['ak47',
                         'american flag',
                         'backpack',
                         'baseball bat',
                         'baseball glove',
                         'basketball hoop',
                         'bat',
                         'bathtub',
                         'bear',
                         'beer mug',
                         'billiards',
                         'binoculars',
                         'birdbath',
                         'blimp',
                         'bonsai',
                         'boom box',
                         'bowling ball',
                         'bowling pin',
                         'boxing glove',
                         'brain',
                         'breadmaker',
                         'buddha',
                         'bulldozer',
                         'butterfly',
                         'cactus',
                         'cake',
                         'calculator',
                         'camel',
                         'cannon',
                         'canoe',
                         'car tire',
                         'cartman',
                         'cd',
                         'centipede',
                         'cereal box',
                         'chandelier',
                         'chess board',
                         'chimp',
                         'chopsticks',
                         'cockroach',
                         'coffee mug',
                         'coffin',
                         'coin',
                         'comet',
                         'computer keyboard',
                         'computer monitor',
                         'computer mouse',
                         'conch',
                         'cormorant',
                         'covered wagon',
                         'cowboy hat',
                         'crab',
                         'desk globe',
                         'diamond ring',
                         'dice',
                         'dog',
                         'dolphin',
                         'doorknob',
                         'drinking straw',
                         'duck',
                         'dumb bell',
                         'eiffel tower',
                         'electric guitar',
                         'elephant',
                         'elk',
                         'ewer',
                         'eyeglasses',
                         'fern',
                         'fighter jet',
                         'fire extinguisher',
                         'fire hydrant',
                         'fire truck',
                         'fireworks',
                         'flashlight',
                         'floppy disk',
                         'football helmet',
                         'french horn',
                         'fried egg',
                         'frisbee',
                         'frog',
                         'frying pan',
                         'galaxy',
                         'gas pump',
                         'giraffe',
                         'goat',
                         'golden gate bridge',
                         'goldfish',
                         'golf ball',
                         'goose',
                         'gorilla',
                         'grand piano',
                         'grapes',
                         'grasshopper',
                         'guitar pick',
                         'hamburger',
                         'hammock',
                         'harmonica',
                         'harp',
                         'harpsichord',
                         'hawksbill',
                         'head phones',
                         'helicopter',
                         'hibiscus',
                         'homer simpson',
                         'horse',
                         'horseshoe crab',
                         'hot air balloon',
                         'hot dog',
                         'hot tub',
                         'hourglass',
                         'house fly',
                         'human skeleton',
                         'hummingbird',
                         'ibis',
                         'ice cream cone',
                         'iguana',
                         'ipod',
                         'iris',
                         'jesus christ',
                         'joy stick',
                         'kangaroo',
                         'kayak',
                         'ketch',
                         'killer whale',
                         'knife',
                         'ladder',
                         'laptop',
                         'lathe',
                         'leopards',
                         'license plate',
                         'lightbulb',
                         'light house',
                         'lightning',
                         'llama',
                         'mailbox',
                         'mandolin',
                         'mars',
                         'mattress',
                         'megaphone',
                         'menorah',
                         'microscope',
                         'microwave',
                         'minaret',
                         'minotaur',
                         'motorbikes',
                         'mountain bike',
                         'mushroom',
                         'mussels',
                         'necktie',
                         'octopus',
                         'ostrich',
                         'owl',
                         'palm pilot',
                         'palm tree',
                         'paperclip',
                         'paper shredder',
                         'pci card',
                         'penguin',
                         'people',
                         'pez dispenser',
                         'photocopier',
                         'picnic table',
                         'playing card',
                         'porcupine',
                         'pram',
                         'praying mantis',
                         'pyramid',
                         'raccoon',
                         'radio telescope',
                         'rainbow',
                         'refrigerator',
                         'revolver',
                         'rifle',
                         'rotary phone',
                         'roulette wheel',
                         'saddle',
                         'saturn',
                         'school bus',
                         'scorpion',
                         'screwdriver',
                         'segway',
                         'self propelled lawn mower',
                         'sextant',
                         'sheet music',
                         'skateboard',
                         'skunk',
                         'skyscraper',
                         'smokestack',
                         'snail',
                         'snake',
                         'sneaker',
                         'snowmobile',
                         'soccer ball',
                         'socks',
                         'soda can',
                         'spaghetti',
                         'speed boat',
                         'spider',
                         'spoon',
                         'stained glass',
                         'starfish',
                         'steering wheel',
                         'stirrups',
                         'sunflower',
                         'superman',
                         'sushi',
                         'swan',
                         'swiss army knife',
                         'sword',
                         'syringe',
                         'tambourine',
                         'teapot',
                         'teddy bear',
                         'teepee',
                         'telephone box',
                         'tennis ball',
                         'tennis court',
                         'tennis racket',
                         'theodolite',
                         'toaster',
                         'tomato',
                         'tombstone',
                         'top hat',
                         'touring bike',
                         'tower pisa',
                         'traffic light',
                         'treadmill',
                         'triceratops',
                         'tricycle',
                         'trilobite',
                         'tripod',
                         't shirt',
                         'tuning fork',
                         'tweezer',
                         'umbrella',
                         'unicorn',
                         'vcr',
                         'video projector',
                         'washing machine',
                         'watch',
                         'waterfall',
                         'watermelon',
                         'welding mask',
                         'wheelbarrow',
                         'windmill',
                         'wine bottle',
                         'xylophone',
                         'yarmulke',
                         'yo yo',
                         'zebra',
                         'airplanes',
                         'car side',
                         'faces easy',
                         'greyhound',
                         'tennis shoes',
                         'toad']
