import torch
import sys
from collections import OrderedDict

# ours = torch.load('/mnt/shadow_cv_training/mingzhenzhu/ClipDistiller/pretrained/clipdistv7_D_imagenet_T_clipr50_S_mnv2_ep90.pth')
#
# mnv2_torchvision = torch.load('/mnt/shadow_cv_training/mingzhenzhu/ClipDistiller/pretrained/mobilenet_v2-b0353104.pth')
# # mnv2_torchvision = list(mnv2_torchvision.keys())
# mnv2_mmdet = torch.load('/mnt/shadow_cv_training/mingzhenzhu/ClipDistiller/pretrained/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth')
# # mnv2_mmdet = list(mnv2_mmdet['state_dict'].keys())
# mnv2_mmdet = mnv2_mmdet['state_dict']
# # print(len(mnv2_torchvision))
# # print(len(mnv2_mmdet))
#
# dict_mnv2_tv = []
# dict_mnv2_mmdet = []
# for k, v in mnv2_torchvision.items():
#     dict_mnv2_tv.append(k)
#
# for k, v in mnv2_mmdet.items():
#     dict_mnv2_mmdet.append(k)
#
# # print(dict_mnv2_tv)
# # print(dict_mnv2_mmdet)
# for i in range(len(dict_mnv2_mmdet)):
#     print('\''+ dict_mnv2_tv[i]+'\''+': '+'\''+dict_mnv2_mmdet[i].replace('backbone.', '')+'\',')

mnv2_torchvision_to_mmdet = {
    'features.0.0.weight': 'conv1.conv.weight',
    'features.0.1.weight': 'conv1.bn.weight',
    'features.0.1.bias': 'conv1.bn.bias',
    'features.0.1.running_mean': 'conv1.bn.running_mean',
    'features.0.1.running_var': 'conv1.bn.running_var',
    'features.0.1.num_batches_tracked': 'conv1.bn.num_batches_tracked',
    'features.1.conv.0.0.weight': 'layer1.0.conv.0.conv.weight',
    'features.1.conv.0.1.weight': 'layer1.0.conv.0.bn.weight',
    'features.1.conv.0.1.bias': 'layer1.0.conv.0.bn.bias',
    'features.1.conv.0.1.running_mean': 'layer1.0.conv.0.bn.running_mean',
    'features.1.conv.0.1.running_var': 'layer1.0.conv.0.bn.running_var',
    'features.1.conv.0.1.num_batches_tracked': 'layer1.0.conv.0.bn.num_batches_tracked',
    'features.1.conv.1.weight': 'layer1.0.conv.1.conv.weight',
    'features.1.conv.2.weight': 'layer1.0.conv.1.bn.weight',
    'features.1.conv.2.bias': 'layer1.0.conv.1.bn.bias',
    'features.1.conv.2.running_mean': 'layer1.0.conv.1.bn.running_mean',
    'features.1.conv.2.running_var': 'layer1.0.conv.1.bn.running_var',
    'features.1.conv.2.num_batches_tracked': 'layer1.0.conv.1.bn.num_batches_tracked',
    'features.2.conv.0.0.weight': 'layer2.0.conv.0.conv.weight',
    'features.2.conv.0.1.weight': 'layer2.0.conv.0.bn.weight',
    'features.2.conv.0.1.bias': 'layer2.0.conv.0.bn.bias',
    'features.2.conv.0.1.running_mean': 'layer2.0.conv.0.bn.running_mean',
    'features.2.conv.0.1.running_var': 'layer2.0.conv.0.bn.running_var',
    'features.2.conv.0.1.num_batches_tracked': 'layer2.0.conv.0.bn.num_batches_tracked',
    'features.2.conv.1.0.weight': 'layer2.0.conv.1.conv.weight',
    'features.2.conv.1.1.weight': 'layer2.0.conv.1.bn.weight',
    'features.2.conv.1.1.bias': 'layer2.0.conv.1.bn.bias',
    'features.2.conv.1.1.running_mean': 'layer2.0.conv.1.bn.running_mean',
    'features.2.conv.1.1.running_var': 'layer2.0.conv.1.bn.running_var',
    'features.2.conv.1.1.num_batches_tracked': 'layer2.0.conv.1.bn.num_batches_tracked',
    'features.2.conv.2.weight': 'layer2.0.conv.2.conv.weight',
    'features.2.conv.3.weight': 'layer2.0.conv.2.bn.weight',
    'features.2.conv.3.bias': 'layer2.0.conv.2.bn.bias',
    'features.2.conv.3.running_mean': 'layer2.0.conv.2.bn.running_mean',
    'features.2.conv.3.running_var': 'layer2.0.conv.2.bn.running_var',
    'features.2.conv.3.num_batches_tracked': 'layer2.0.conv.2.bn.num_batches_tracked',
    'features.3.conv.0.0.weight': 'layer2.1.conv.0.conv.weight',
    'features.3.conv.0.1.weight': 'layer2.1.conv.0.bn.weight',
    'features.3.conv.0.1.bias': 'layer2.1.conv.0.bn.bias',
    'features.3.conv.0.1.running_mean': 'layer2.1.conv.0.bn.running_mean',
    'features.3.conv.0.1.running_var': 'layer2.1.conv.0.bn.running_var',
    'features.3.conv.0.1.num_batches_tracked': 'layer2.1.conv.0.bn.num_batches_tracked',
    'features.3.conv.1.0.weight': 'layer2.1.conv.1.conv.weight',
    'features.3.conv.1.1.weight': 'layer2.1.conv.1.bn.weight',
    'features.3.conv.1.1.bias': 'layer2.1.conv.1.bn.bias',
    'features.3.conv.1.1.running_mean': 'layer2.1.conv.1.bn.running_mean',
    'features.3.conv.1.1.running_var': 'layer2.1.conv.1.bn.running_var',
    'features.3.conv.1.1.num_batches_tracked': 'layer2.1.conv.1.bn.num_batches_tracked',
    'features.3.conv.2.weight': 'layer2.1.conv.2.conv.weight',
    'features.3.conv.3.weight': 'layer2.1.conv.2.bn.weight',
    'features.3.conv.3.bias': 'layer2.1.conv.2.bn.bias',
    'features.3.conv.3.running_mean': 'layer2.1.conv.2.bn.running_mean',
    'features.3.conv.3.running_var': 'layer2.1.conv.2.bn.running_var',
    'features.3.conv.3.num_batches_tracked': 'layer2.1.conv.2.bn.num_batches_tracked',
    'features.4.conv.0.0.weight': 'layer3.0.conv.0.conv.weight',
    'features.4.conv.0.1.weight': 'layer3.0.conv.0.bn.weight',
    'features.4.conv.0.1.bias': 'layer3.0.conv.0.bn.bias',
    'features.4.conv.0.1.running_mean': 'layer3.0.conv.0.bn.running_mean',
    'features.4.conv.0.1.running_var': 'layer3.0.conv.0.bn.running_var',
    'features.4.conv.0.1.num_batches_tracked': 'layer3.0.conv.0.bn.num_batches_tracked',
    'features.4.conv.1.0.weight': 'layer3.0.conv.1.conv.weight',
    'features.4.conv.1.1.weight': 'layer3.0.conv.1.bn.weight',
    'features.4.conv.1.1.bias': 'layer3.0.conv.1.bn.bias',
    'features.4.conv.1.1.running_mean': 'layer3.0.conv.1.bn.running_mean',
    'features.4.conv.1.1.running_var': 'layer3.0.conv.1.bn.running_var',
    'features.4.conv.1.1.num_batches_tracked': 'layer3.0.conv.1.bn.num_batches_tracked',
    'features.4.conv.2.weight': 'layer3.0.conv.2.conv.weight',
    'features.4.conv.3.weight': 'layer3.0.conv.2.bn.weight',
    'features.4.conv.3.bias': 'layer3.0.conv.2.bn.bias',
    'features.4.conv.3.running_mean': 'layer3.0.conv.2.bn.running_mean',
    'features.4.conv.3.running_var': 'layer3.0.conv.2.bn.running_var',
    'features.4.conv.3.num_batches_tracked': 'layer3.0.conv.2.bn.num_batches_tracked',
    'features.5.conv.0.0.weight': 'layer3.1.conv.0.conv.weight',
    'features.5.conv.0.1.weight': 'layer3.1.conv.0.bn.weight',
    'features.5.conv.0.1.bias': 'layer3.1.conv.0.bn.bias',
    'features.5.conv.0.1.running_mean': 'layer3.1.conv.0.bn.running_mean',
    'features.5.conv.0.1.running_var': 'layer3.1.conv.0.bn.running_var',
    'features.5.conv.0.1.num_batches_tracked': 'layer3.1.conv.0.bn.num_batches_tracked',
    'features.5.conv.1.0.weight': 'layer3.1.conv.1.conv.weight',
    'features.5.conv.1.1.weight': 'layer3.1.conv.1.bn.weight',
    'features.5.conv.1.1.bias': 'layer3.1.conv.1.bn.bias',
    'features.5.conv.1.1.running_mean': 'layer3.1.conv.1.bn.running_mean',
    'features.5.conv.1.1.running_var': 'layer3.1.conv.1.bn.running_var',
    'features.5.conv.1.1.num_batches_tracked': 'layer3.1.conv.1.bn.num_batches_tracked',
    'features.5.conv.2.weight': 'layer3.1.conv.2.conv.weight',
    'features.5.conv.3.weight': 'layer3.1.conv.2.bn.weight',
    'features.5.conv.3.bias': 'layer3.1.conv.2.bn.bias',
    'features.5.conv.3.running_mean': 'layer3.1.conv.2.bn.running_mean',
    'features.5.conv.3.running_var': 'layer3.1.conv.2.bn.running_var',
    'features.5.conv.3.num_batches_tracked': 'layer3.1.conv.2.bn.num_batches_tracked',
    'features.6.conv.0.0.weight': 'layer3.2.conv.0.conv.weight',
    'features.6.conv.0.1.weight': 'layer3.2.conv.0.bn.weight',
    'features.6.conv.0.1.bias': 'layer3.2.conv.0.bn.bias',
    'features.6.conv.0.1.running_mean': 'layer3.2.conv.0.bn.running_mean',
    'features.6.conv.0.1.running_var': 'layer3.2.conv.0.bn.running_var',
    'features.6.conv.0.1.num_batches_tracked': 'layer3.2.conv.0.bn.num_batches_tracked',
    'features.6.conv.1.0.weight': 'layer3.2.conv.1.conv.weight',
    'features.6.conv.1.1.weight': 'layer3.2.conv.1.bn.weight',
    'features.6.conv.1.1.bias': 'layer3.2.conv.1.bn.bias',
    'features.6.conv.1.1.running_mean': 'layer3.2.conv.1.bn.running_mean',
    'features.6.conv.1.1.running_var': 'layer3.2.conv.1.bn.running_var',
    'features.6.conv.1.1.num_batches_tracked': 'layer3.2.conv.1.bn.num_batches_tracked',
    'features.6.conv.2.weight': 'layer3.2.conv.2.conv.weight',
    'features.6.conv.3.weight': 'layer3.2.conv.2.bn.weight',
    'features.6.conv.3.bias': 'layer3.2.conv.2.bn.bias',
    'features.6.conv.3.running_mean': 'layer3.2.conv.2.bn.running_mean',
    'features.6.conv.3.running_var': 'layer3.2.conv.2.bn.running_var',
    'features.6.conv.3.num_batches_tracked': 'layer3.2.conv.2.bn.num_batches_tracked',
    'features.7.conv.0.0.weight': 'layer4.0.conv.0.conv.weight',
    'features.7.conv.0.1.weight': 'layer4.0.conv.0.bn.weight',
    'features.7.conv.0.1.bias': 'layer4.0.conv.0.bn.bias',
    'features.7.conv.0.1.running_mean': 'layer4.0.conv.0.bn.running_mean',
    'features.7.conv.0.1.running_var': 'layer4.0.conv.0.bn.running_var',
    'features.7.conv.0.1.num_batches_tracked': 'layer4.0.conv.0.bn.num_batches_tracked',
    'features.7.conv.1.0.weight': 'layer4.0.conv.1.conv.weight',
    'features.7.conv.1.1.weight': 'layer4.0.conv.1.bn.weight',
    'features.7.conv.1.1.bias': 'layer4.0.conv.1.bn.bias',
    'features.7.conv.1.1.running_mean': 'layer4.0.conv.1.bn.running_mean',
    'features.7.conv.1.1.running_var': 'layer4.0.conv.1.bn.running_var',
    'features.7.conv.1.1.num_batches_tracked': 'layer4.0.conv.1.bn.num_batches_tracked',
    'features.7.conv.2.weight': 'layer4.0.conv.2.conv.weight',
    'features.7.conv.3.weight': 'layer4.0.conv.2.bn.weight',
    'features.7.conv.3.bias': 'layer4.0.conv.2.bn.bias',
    'features.7.conv.3.running_mean': 'layer4.0.conv.2.bn.running_mean',
    'features.7.conv.3.running_var': 'layer4.0.conv.2.bn.running_var',
    'features.7.conv.3.num_batches_tracked': 'layer4.0.conv.2.bn.num_batches_tracked',
    'features.8.conv.0.0.weight': 'layer4.1.conv.0.conv.weight',
    'features.8.conv.0.1.weight': 'layer4.1.conv.0.bn.weight',
    'features.8.conv.0.1.bias': 'layer4.1.conv.0.bn.bias',
    'features.8.conv.0.1.running_mean': 'layer4.1.conv.0.bn.running_mean',
    'features.8.conv.0.1.running_var': 'layer4.1.conv.0.bn.running_var',
    'features.8.conv.0.1.num_batches_tracked': 'layer4.1.conv.0.bn.num_batches_tracked',
    'features.8.conv.1.0.weight': 'layer4.1.conv.1.conv.weight',
    'features.8.conv.1.1.weight': 'layer4.1.conv.1.bn.weight',
    'features.8.conv.1.1.bias': 'layer4.1.conv.1.bn.bias',
    'features.8.conv.1.1.running_mean': 'layer4.1.conv.1.bn.running_mean',
    'features.8.conv.1.1.running_var': 'layer4.1.conv.1.bn.running_var',
    'features.8.conv.1.1.num_batches_tracked': 'layer4.1.conv.1.bn.num_batches_tracked',
    'features.8.conv.2.weight': 'layer4.1.conv.2.conv.weight',
    'features.8.conv.3.weight': 'layer4.1.conv.2.bn.weight',
    'features.8.conv.3.bias': 'layer4.1.conv.2.bn.bias',
    'features.8.conv.3.running_mean': 'layer4.1.conv.2.bn.running_mean',
    'features.8.conv.3.running_var': 'layer4.1.conv.2.bn.running_var',
    'features.8.conv.3.num_batches_tracked': 'layer4.1.conv.2.bn.num_batches_tracked',
    'features.9.conv.0.0.weight': 'layer4.2.conv.0.conv.weight',
    'features.9.conv.0.1.weight': 'layer4.2.conv.0.bn.weight',
    'features.9.conv.0.1.bias': 'layer4.2.conv.0.bn.bias',
    'features.9.conv.0.1.running_mean': 'layer4.2.conv.0.bn.running_mean',
    'features.9.conv.0.1.running_var': 'layer4.2.conv.0.bn.running_var',
    'features.9.conv.0.1.num_batches_tracked': 'layer4.2.conv.0.bn.num_batches_tracked',
    'features.9.conv.1.0.weight': 'layer4.2.conv.1.conv.weight',
    'features.9.conv.1.1.weight': 'layer4.2.conv.1.bn.weight',
    'features.9.conv.1.1.bias': 'layer4.2.conv.1.bn.bias',
    'features.9.conv.1.1.running_mean': 'layer4.2.conv.1.bn.running_mean',
    'features.9.conv.1.1.running_var': 'layer4.2.conv.1.bn.running_var',
    'features.9.conv.1.1.num_batches_tracked': 'layer4.2.conv.1.bn.num_batches_tracked',
    'features.9.conv.2.weight': 'layer4.2.conv.2.conv.weight',
    'features.9.conv.3.weight': 'layer4.2.conv.2.bn.weight',
    'features.9.conv.3.bias': 'layer4.2.conv.2.bn.bias',
    'features.9.conv.3.running_mean': 'layer4.2.conv.2.bn.running_mean',
    'features.9.conv.3.running_var': 'layer4.2.conv.2.bn.running_var',
    'features.9.conv.3.num_batches_tracked': 'layer4.2.conv.2.bn.num_batches_tracked',
    'features.10.conv.0.0.weight': 'layer4.3.conv.0.conv.weight',
    'features.10.conv.0.1.weight': 'layer4.3.conv.0.bn.weight',
    'features.10.conv.0.1.bias': 'layer4.3.conv.0.bn.bias',
    'features.10.conv.0.1.running_mean': 'layer4.3.conv.0.bn.running_mean',
    'features.10.conv.0.1.running_var': 'layer4.3.conv.0.bn.running_var',
    'features.10.conv.0.1.num_batches_tracked': 'layer4.3.conv.0.bn.num_batches_tracked',
    'features.10.conv.1.0.weight': 'layer4.3.conv.1.conv.weight',
    'features.10.conv.1.1.weight': 'layer4.3.conv.1.bn.weight',
    'features.10.conv.1.1.bias': 'layer4.3.conv.1.bn.bias',
    'features.10.conv.1.1.running_mean': 'layer4.3.conv.1.bn.running_mean',
    'features.10.conv.1.1.running_var': 'layer4.3.conv.1.bn.running_var',
    'features.10.conv.1.1.num_batches_tracked': 'layer4.3.conv.1.bn.num_batches_tracked',
    'features.10.conv.2.weight': 'layer4.3.conv.2.conv.weight',
    'features.10.conv.3.weight': 'layer4.3.conv.2.bn.weight',
    'features.10.conv.3.bias': 'layer4.3.conv.2.bn.bias',
    'features.10.conv.3.running_mean': 'layer4.3.conv.2.bn.running_mean',
    'features.10.conv.3.running_var': 'layer4.3.conv.2.bn.running_var',
    'features.10.conv.3.num_batches_tracked': 'layer4.3.conv.2.bn.num_batches_tracked',
    'features.11.conv.0.0.weight': 'layer5.0.conv.0.conv.weight',
    'features.11.conv.0.1.weight': 'layer5.0.conv.0.bn.weight',
    'features.11.conv.0.1.bias': 'layer5.0.conv.0.bn.bias',
    'features.11.conv.0.1.running_mean': 'layer5.0.conv.0.bn.running_mean',
    'features.11.conv.0.1.running_var': 'layer5.0.conv.0.bn.running_var',
    'features.11.conv.0.1.num_batches_tracked': 'layer5.0.conv.0.bn.num_batches_tracked',
    'features.11.conv.1.0.weight': 'layer5.0.conv.1.conv.weight',
    'features.11.conv.1.1.weight': 'layer5.0.conv.1.bn.weight',
    'features.11.conv.1.1.bias': 'layer5.0.conv.1.bn.bias',
    'features.11.conv.1.1.running_mean': 'layer5.0.conv.1.bn.running_mean',
    'features.11.conv.1.1.running_var': 'layer5.0.conv.1.bn.running_var',
    'features.11.conv.1.1.num_batches_tracked': 'layer5.0.conv.1.bn.num_batches_tracked',
    'features.11.conv.2.weight': 'layer5.0.conv.2.conv.weight',
    'features.11.conv.3.weight': 'layer5.0.conv.2.bn.weight',
    'features.11.conv.3.bias': 'layer5.0.conv.2.bn.bias',
    'features.11.conv.3.running_mean': 'layer5.0.conv.2.bn.running_mean',
    'features.11.conv.3.running_var': 'layer5.0.conv.2.bn.running_var',
    'features.11.conv.3.num_batches_tracked': 'layer5.0.conv.2.bn.num_batches_tracked',
    'features.12.conv.0.0.weight': 'layer5.1.conv.0.conv.weight',
    'features.12.conv.0.1.weight': 'layer5.1.conv.0.bn.weight',
    'features.12.conv.0.1.bias': 'layer5.1.conv.0.bn.bias',
    'features.12.conv.0.1.running_mean': 'layer5.1.conv.0.bn.running_mean',
    'features.12.conv.0.1.running_var': 'layer5.1.conv.0.bn.running_var',
    'features.12.conv.0.1.num_batches_tracked': 'layer5.1.conv.0.bn.num_batches_tracked',
    'features.12.conv.1.0.weight': 'layer5.1.conv.1.conv.weight',
    'features.12.conv.1.1.weight': 'layer5.1.conv.1.bn.weight',
    'features.12.conv.1.1.bias': 'layer5.1.conv.1.bn.bias',
    'features.12.conv.1.1.running_mean': 'layer5.1.conv.1.bn.running_mean',
    'features.12.conv.1.1.running_var': 'layer5.1.conv.1.bn.running_var',
    'features.12.conv.1.1.num_batches_tracked': 'layer5.1.conv.1.bn.num_batches_tracked',
    'features.12.conv.2.weight': 'layer5.1.conv.2.conv.weight',
    'features.12.conv.3.weight': 'layer5.1.conv.2.bn.weight',
    'features.12.conv.3.bias': 'layer5.1.conv.2.bn.bias',
    'features.12.conv.3.running_mean': 'layer5.1.conv.2.bn.running_mean',
    'features.12.conv.3.running_var': 'layer5.1.conv.2.bn.running_var',
    'features.12.conv.3.num_batches_tracked': 'layer5.1.conv.2.bn.num_batches_tracked',
    'features.13.conv.0.0.weight': 'layer5.2.conv.0.conv.weight',
    'features.13.conv.0.1.weight': 'layer5.2.conv.0.bn.weight',
    'features.13.conv.0.1.bias': 'layer5.2.conv.0.bn.bias',
    'features.13.conv.0.1.running_mean': 'layer5.2.conv.0.bn.running_mean',
    'features.13.conv.0.1.running_var': 'layer5.2.conv.0.bn.running_var',
    'features.13.conv.0.1.num_batches_tracked': 'layer5.2.conv.0.bn.num_batches_tracked',
    'features.13.conv.1.0.weight': 'layer5.2.conv.1.conv.weight',
    'features.13.conv.1.1.weight': 'layer5.2.conv.1.bn.weight',
    'features.13.conv.1.1.bias': 'layer5.2.conv.1.bn.bias',
    'features.13.conv.1.1.running_mean': 'layer5.2.conv.1.bn.running_mean',
    'features.13.conv.1.1.running_var': 'layer5.2.conv.1.bn.running_var',
    'features.13.conv.1.1.num_batches_tracked': 'layer5.2.conv.1.bn.num_batches_tracked',
    'features.13.conv.2.weight': 'layer5.2.conv.2.conv.weight',
    'features.13.conv.3.weight': 'layer5.2.conv.2.bn.weight',
    'features.13.conv.3.bias': 'layer5.2.conv.2.bn.bias',
    'features.13.conv.3.running_mean': 'layer5.2.conv.2.bn.running_mean',
    'features.13.conv.3.running_var': 'layer5.2.conv.2.bn.running_var',
    'features.13.conv.3.num_batches_tracked': 'layer5.2.conv.2.bn.num_batches_tracked',
    'features.14.conv.0.0.weight': 'layer6.0.conv.0.conv.weight',
    'features.14.conv.0.1.weight': 'layer6.0.conv.0.bn.weight',
    'features.14.conv.0.1.bias': 'layer6.0.conv.0.bn.bias',
    'features.14.conv.0.1.running_mean': 'layer6.0.conv.0.bn.running_mean',
    'features.14.conv.0.1.running_var': 'layer6.0.conv.0.bn.running_var',
    'features.14.conv.0.1.num_batches_tracked': 'layer6.0.conv.0.bn.num_batches_tracked',
    'features.14.conv.1.0.weight': 'layer6.0.conv.1.conv.weight',
    'features.14.conv.1.1.weight': 'layer6.0.conv.1.bn.weight',
    'features.14.conv.1.1.bias': 'layer6.0.conv.1.bn.bias',
    'features.14.conv.1.1.running_mean': 'layer6.0.conv.1.bn.running_mean',
    'features.14.conv.1.1.running_var': 'layer6.0.conv.1.bn.running_var',
    'features.14.conv.1.1.num_batches_tracked': 'layer6.0.conv.1.bn.num_batches_tracked',
    'features.14.conv.2.weight': 'layer6.0.conv.2.conv.weight',
    'features.14.conv.3.weight': 'layer6.0.conv.2.bn.weight',
    'features.14.conv.3.bias': 'layer6.0.conv.2.bn.bias',
    'features.14.conv.3.running_mean': 'layer6.0.conv.2.bn.running_mean',
    'features.14.conv.3.running_var': 'layer6.0.conv.2.bn.running_var',
    'features.14.conv.3.num_batches_tracked': 'layer6.0.conv.2.bn.num_batches_tracked',
    'features.15.conv.0.0.weight': 'layer6.1.conv.0.conv.weight',
    'features.15.conv.0.1.weight': 'layer6.1.conv.0.bn.weight',
    'features.15.conv.0.1.bias': 'layer6.1.conv.0.bn.bias',
    'features.15.conv.0.1.running_mean': 'layer6.1.conv.0.bn.running_mean',
    'features.15.conv.0.1.running_var': 'layer6.1.conv.0.bn.running_var',
    'features.15.conv.0.1.num_batches_tracked': 'layer6.1.conv.0.bn.num_batches_tracked',
    'features.15.conv.1.0.weight': 'layer6.1.conv.1.conv.weight',
    'features.15.conv.1.1.weight': 'layer6.1.conv.1.bn.weight',
    'features.15.conv.1.1.bias': 'layer6.1.conv.1.bn.bias',
    'features.15.conv.1.1.running_mean': 'layer6.1.conv.1.bn.running_mean',
    'features.15.conv.1.1.running_var': 'layer6.1.conv.1.bn.running_var',
    'features.15.conv.1.1.num_batches_tracked': 'layer6.1.conv.1.bn.num_batches_tracked',
    'features.15.conv.2.weight': 'layer6.1.conv.2.conv.weight',
    'features.15.conv.3.weight': 'layer6.1.conv.2.bn.weight',
    'features.15.conv.3.bias': 'layer6.1.conv.2.bn.bias',
    'features.15.conv.3.running_mean': 'layer6.1.conv.2.bn.running_mean',
    'features.15.conv.3.running_var': 'layer6.1.conv.2.bn.running_var',
    'features.15.conv.3.num_batches_tracked': 'layer6.1.conv.2.bn.num_batches_tracked',
    'features.16.conv.0.0.weight': 'layer6.2.conv.0.conv.weight',
    'features.16.conv.0.1.weight': 'layer6.2.conv.0.bn.weight',
    'features.16.conv.0.1.bias': 'layer6.2.conv.0.bn.bias',
    'features.16.conv.0.1.running_mean': 'layer6.2.conv.0.bn.running_mean',
    'features.16.conv.0.1.running_var': 'layer6.2.conv.0.bn.running_var',
    'features.16.conv.0.1.num_batches_tracked': 'layer6.2.conv.0.bn.num_batches_tracked',
    'features.16.conv.1.0.weight': 'layer6.2.conv.1.conv.weight',
    'features.16.conv.1.1.weight': 'layer6.2.conv.1.bn.weight',
    'features.16.conv.1.1.bias': 'layer6.2.conv.1.bn.bias',
    'features.16.conv.1.1.running_mean': 'layer6.2.conv.1.bn.running_mean',
    'features.16.conv.1.1.running_var': 'layer6.2.conv.1.bn.running_var',
    'features.16.conv.1.1.num_batches_tracked': 'layer6.2.conv.1.bn.num_batches_tracked',
    'features.16.conv.2.weight': 'layer6.2.conv.2.conv.weight',
    'features.16.conv.3.weight': 'layer6.2.conv.2.bn.weight',
    'features.16.conv.3.bias': 'layer6.2.conv.2.bn.bias',
    'features.16.conv.3.running_mean': 'layer6.2.conv.2.bn.running_mean',
    'features.16.conv.3.running_var': 'layer6.2.conv.2.bn.running_var',
    'features.16.conv.3.num_batches_tracked': 'layer6.2.conv.2.bn.num_batches_tracked',
    'features.17.conv.0.0.weight': 'layer7.0.conv.0.conv.weight',
    'features.17.conv.0.1.weight': 'layer7.0.conv.0.bn.weight',
    'features.17.conv.0.1.bias': 'layer7.0.conv.0.bn.bias',
    'features.17.conv.0.1.running_mean': 'layer7.0.conv.0.bn.running_mean',
    'features.17.conv.0.1.running_var': 'layer7.0.conv.0.bn.running_var',
    'features.17.conv.0.1.num_batches_tracked': 'layer7.0.conv.0.bn.num_batches_tracked',
    'features.17.conv.1.0.weight': 'layer7.0.conv.1.conv.weight',
    'features.17.conv.1.1.weight': 'layer7.0.conv.1.bn.weight',
    'features.17.conv.1.1.bias': 'layer7.0.conv.1.bn.bias',
    'features.17.conv.1.1.running_mean': 'layer7.0.conv.1.bn.running_mean',
    'features.17.conv.1.1.running_var': 'layer7.0.conv.1.bn.running_var',
    'features.17.conv.1.1.num_batches_tracked': 'layer7.0.conv.1.bn.num_batches_tracked',
    'features.17.conv.2.weight': 'layer7.0.conv.2.conv.weight',
    'features.17.conv.3.weight': 'layer7.0.conv.2.bn.weight',
    'features.17.conv.3.bias': 'layer7.0.conv.2.bn.bias',
    'features.17.conv.3.running_mean': 'layer7.0.conv.2.bn.running_mean',
    'features.17.conv.3.running_var': 'layer7.0.conv.2.bn.running_var',
    'features.17.conv.3.num_batches_tracked': 'layer7.0.conv.2.bn.num_batches_tracked',
    'features.18.0.weight': 'conv2.conv.weight',
    'features.18.1.weight': 'conv2.bn.weight',
    'features.18.1.bias': 'conv2.bn.bias',
    'features.18.1.running_mean': 'conv2.bn.running_mean',
    'features.18.1.running_var': 'conv2.bn.running_var',
    'features.18.1.num_batches_tracked': 'conv2.bn.num_batches_tracked',
    'classifier.1.weight': 'head.fc.weight',
    'classifier.1.bias': 'head.fc.bias',
}


if __name__ == "__main__":
    input = sys.argv[1]

    obj = torch.load(input, map_location="cpu")
    # obj = obj["state_dict"]

    newmodel = {}
    for k, v in obj.items():
        if k not in mnv2_torchvision_to_mmdet:
            continue
        old_k = k
        k = mnv2_torchvision_to_mmdet[k]
        print(old_k, "->", k)
        newmodel[k] = v

    res = {"state_dict": newmodel, "__author__": "mingzhenzhu"}

    torch.save(res, sys.argv[2])